"""tenants, keys and events

Revision ID: c4ec13dedff2
Revises:
Create Date: 2026-10-06 17:27:04.082842

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4ec13dedff2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("prefix", sa.String(length=20), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_prefix"), ["prefix"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_keys_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("api_key_id", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("decided", sa.String(length=10), nullable=False),
        sa.Column("action", sa.String(length=10), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("upstream_status", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_api_key_id"), ["api_key_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "event_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "category"),
    )
    with op.batch_alter_table("event_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_categories_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_categories_event_id"), ["event_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_categories_event_id"))
        batch_op.drop_index(batch_op.f("ix_event_categories_category"))

    op.drop_table("event_categories")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_events_at"))
        batch_op.drop_index(batch_op.f("ix_events_api_key_id"))
        batch_op.drop_index(batch_op.f("ix_events_action"))

    op.drop_table("events")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_prefix"))

    op.drop_table("api_keys")
    op.drop_table("tenants")
    # ### end Alembic commands ###
